exclude prefill from calculating TPOT statistics
openvinotoolkit/openvino.genai pull request #1118
Opened 2024-10-31 13:49 UTC by pavel-esir

CVS-155098

2024-10-31 17:36 UTC, Wovchena requested changes

2024-11-01 16:54 UTC, pavel-esir commented on src/python/py_perf_metrics.cpp
> +    // Use double instead of float to store more than 7 signficant digits.
Because the current timestamp (number of secs from 1970) is already 11 digits :) Will add sentence to comment

2024-11-01 16:55 UTC, pavel-esir commented on src/cpp/src/perf_metrics.cpp
> +        // The very first duration used to calcualte TPOT is from the first token to the second token,
agreed

2024-11-01 16:59 UTC, pavel-esir commented on src/cpp/src/perf_metrics.cpp
> +        // Exclude prefill from calculating TPOT.
Isn't it obvious what prefill mean? If someone got to this place he/she should already know what it's meant by prefill?

2024-11-01 16:59 UTC, pavel-esir commented on src/README.md
> +print(f'Timestamps: {" ms, ".join(f"{i:.2f}" for i in raw_metrics.m_new_token_times[1:])}')
left `[1:]` by mistake, will remove that

2024-11-01 17:55 UTC, pavel-esir commented on src/python/py_perf_metrics.cpp
> +    // Use double instead of float to store more than 7 signficant digits.
added explanation, for ms we need at least 14 digits

2024-11-01 17:57 UTC, pavel-esir commented on src/cpp/src/perf_metrics.cpp
> +        // The very first duration used to calcualte TPOT is from the first token to the second token,
rephrased this sentence keeping `must`

2024-11-01 17:59 UTC, pavel-esir commented on src/cpp/src/perf_metrics.cpp
> +        // Exclude prefill from calculating TPOT.
Added comprehensive explanation what is refill and why we should not take prefill duration for TPOT

2024-11-01 17:59 UTC, pavel-esir commented on src/README.md
> +print(f'Timestamps: {" ms, ".join(f"{i:.2f}" for i in raw_metrics.m_new_token_times[1:])}')
removed that

2024-11-01 17:59 UTC, pavel-esir commented on src/README.md
> +Additionally to mean and std values, `perf_metrics` object has a `raw_metrics` field which stored raw numbers with timesteps when batch of tokens was generated, with batch sizes for each timestamp, w
rephrased it

2024-11-01 18:00 UTC, pavel-esir commented on src/README.md
> +#### Using raw performance metrics
done

2024-11-03 07:57 UTC, pavel-esir commented on src/README.md
> +pure_inference_duration = np.mean(generate_duration - tok_detok_duration) / 1000 # in seconds
```suggestion
pure_inference_duration = np.sum(generate_duration - tok_detok_duration) / 1000 # in seconds
```

2024-11-04 05:42 UTC, Wovchena commented on src/README.md
> +import openvino_genai as ov_genai
```suggestion
```

2024-11-04 05:45 UTC, Wovchena commented on src/cpp/src/perf_metrics.cpp
> +        // The very first infer request (prefill stage) is slower than sunsequent ones since we process a sequence of tokens.
```suggestion
        // The very first infer request (prefill stage) is slower than subsequent ones since we process a sequence of tokens.
```

2024-11-04 05:48 UTC, Wovchena commented on src/python/py_perf_metrics.cpp
> +    // while float only allows to store ~7 significant digits.
```suggestion
    // while float only allows to store ~7 significant digits.
    // And the current timestamp (number of secs from 1970) is already 11 digits.
```

2024-11-04 08:53 UTC, pavel-esir commented on src/README.md
> +print(f'Generate duration: {perf_metrics.get_generate_duration().mean:.2f}')
```suggestion
print(f'Generate duration: {perf_metrics.get_generate_duration().mean:.2f} ms')
```

2024-11-04 09:05 UTC, Wovchena approved these changes

2024-11-04 12:39 UTC, andrei-kochin commented
Tests will be added in the separate PR once @pavel-esir is back from the vacation

2024-11-05 09:08 UTC, merged