Fix hidden state size for StaticWhisperPipeline
openvinotoolkit/openvino.genai pull request #1179
Opened 2024-11-08 12:35 UTC by eshiryae

2024-11-08 13:39 UTC, TolyaTalamanov commented on src/cpp/src/whisper_pipeline_static.cpp
> +uint32_t get_encoder_hidden_state_size(const std::shared_ptr<ov::Model>& encoder) {
Simply
```
encoder->output("last_hidden_state");
```

2024-11-08 17:51 UTC, soumendukrg requested changes
Need the additional changes needed.

2024-11-08 17:51 UTC, soumendukrg commented on src/cpp/src/whisper_pipeline_static.cpp
> +            return output.get_partial_shape()[1].get_length();
Need to get both dimension 1 and dimension 2 of encoder output. Dim 1 will be 1500. Dim 2 will vary based on model version. For example, dim 2 = 512 for base, 768 for small.

2024-11-08 17:51 UTC, soumendukrg commented on src/cpp/src/whisper_pipeline_static.cpp
> +            new_shape[1] = lhstate_size;  // from encoder output{'last_hidden_state'}
Need to assign new_shape[2] = last_hidden_state.shape[2]

2024-11-08 23:01 UTC, RyanMetcalfeInt8 commented
Can we try to get this fix pulled into releases/2024/5 branch as well?

2024-11-11 07:23 UTC, KingRei reviewed
[whisper_pipeline_static.zip](https://github.com/user-attachments/files/17698557/whisper_pipeline_static.zip)
I added our modification to avoid converting dynamic shape to static shape failure in following reference code.

2024-11-11 10:16 UTC, dmatveev commented
@RyanMetcalfeInt8  propagated to release branch - #1186

2024-11-11 14:30 UTC, dmatveev approved these changes
LGTM

2024-11-11 14:50 UTC, TolyaTalamanov approved these changes

2024-11-12 01:01 UTC, soumendukrg approved these changes
The modifications look good. Thanks.

2024-11-12 01:17 UTC, merged