update sd export for having SDPA
openvinotoolkit/openvino.genai pull request #134
Opened 2024-01-09 10:56 UTC by eaidova

2024-01-09 14:03 UTC, sammysun0711 requested changes

2024-01-09 15:11 UTC, eaidova commented on llm_bench/python/convert.py
>      gc.collect()
moved

2024-01-09 15:13 UTC, eaidova commented on llm_bench/python/convert.py
> +        pt_model = StableDiffusionPipeline.from_pretrained(args.model_id)
I changed order for conversion model, now fp conversion happens before weights compression, so we do not need recreate model

2024-01-09 15:13 UTC, eaidova commented on llm_bench/python/convert.py
> +    models_and_onnx_configs = _get_submodels_for_export_stable_diffusion(pipeline)
fixed, thanks

2024-01-09 15:13 UTC, eaidova commented on llm_bench/python/convert.py
> +    convert_sd_common(pt_model, output_dir)
fixed

2024-01-09 15:13 UTC, eaidova commented on llm_bench/python/convert.py
> +    convert_sd_common(pt_model, output_dir)
fixed

2024-01-09 15:13 UTC, eaidova commented on llm_bench/python/convert.py
>                  )
fixed, thanks

2024-01-09 15:18 UTC, eaidova commented on llm_bench/python/convert.py
> +            compress_option="fp16" if args.precision == "FP16" else None,
fixed, thanks

2024-01-10 01:35 UTC, sammysun0711 commented
LGTM, thanks for your great support!

2024-01-10 01:35 UTC, sammysun0711 approved these changes

2024-01-10 04:34 UTC, merged