Use get_max_new_tokens() insted of max_new_tokens field when stopping…
openvinotoolkit/openvino.genai pull request #1417
Opened 2024-12-20 09:11 UTC by michalkulakowski

… generation

2024-12-20 09:43 UTC, mzegla commented on src/cpp/src/sampler.hpp
> +        void is_done(const ov::genai::GenerationConfig& sampling_params, size_t prompt_len);
I think we can include `prompt_len` information in `Group` members during object construction and avoid passing it as a parameter in this method.

2024-12-20 09:44 UTC, ilya-lavrenov requested changes
Not all places inside `src/cpp` are changed

2024-12-20 09:48 UTC, mzegla commented
One more thing - I believe max_length is now loaded from generation config. Isn't it a model property that is not meant to be a per generation configuration? @michalkulakowski I know you have logic to read that value in OVMS now. Maybe we could move it here and make it a pipeline member. This way it could be used in both OVMS and standalone GenAI app.

2025-01-02 09:52 UTC, michalkulakowski commented
> One more thing - I believe max_length is now loaded from generation config. Isn't it a model property that is not meant to be a per generation configuration? @michalkulakowski I know you have logic to read that value in OVMS now. Maybe we could move it here and make it a pipeline member. This way it could be used in both OVMS and standalone GenAI app.

That makes sense to me. @ilya-lavrenov what do you think?

2025-01-04 08:23 UTC, ilya-lavrenov commented
> One more thing - I believe max_length is now loaded from generation config. Isn't it a model property that is not meant to be a per generation configuration? @michalkulakowski I know you have logic to read that value in OVMS now. Maybe we could move it here and make it a pipeline member. This way it could be used in both OVMS and standalone GenAI app.

I suppose it depends on the model:
- For example for meta-llama/Meta-Llama-3-8B-Instruct we have this value in generation config https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/generation_config.json#L6 
- For other models like default value for max_length is used, which is 20. See https://github.com/huggingface/transformers/blob/e5fd865ebae062b7cf03a81b8c6affeb39f30bec/src/transformers/generation/configuration_utils.py#L127-L129

Looks like max_model_length (which is config.max_position_embeddings, example is https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/config.json#L13) and max_length from generation_config.json are different things, are not they?

2025-01-14 06:28 UTC, michalkulakowski commented
@Wovchena @pavel-esir @as-suvorov  please share your opinion

2025-01-14 06:45 UTC, ilya-lavrenov commented
> @Wovchena @pavel-esir @as-suvorov please share your opinion

I think even w/o default value for max new tokens, we can go with other changes which will respect max_length

2025-02-14 18:05 UTC, as-suvorov commented on src/cpp/src/continuous_batching_impl.cpp
> +        if(sequence_group->get_sampling_parameters().get_max_new_tokens(sequence_group->get_prompt_len()) == 0) {
```suggestion
        if(sequence_group->get_max_new_tokens() == 0) {
```

`SequenceGroup` now has `get_max_new_tokens` method: https://github.com/openvinotoolkit/openvino.genai/blob/master/src/cpp/src/sequence_group.hpp#L702

2025-02-28 08:47 UTC, mzegla approved these changes

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/prompt_lookup/continuous_batching_for_prompt_lookup.cpp
> +                const auto left_generated_len = std::min(sampling_params.get_max_new_tokens(request->get_prompt_len()), sampling_params.max_length) - generated_len - 1;
```suggestion
                const auto left_generated_len = std::min(request->get_max_new_tokens(), sampling_params.max_length) - generated_len - 1;
```

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/sampler.cpp
> +        size_t length = sampling_params.length_penalty > 0.0 ? sequence_group->get_max_new_tokens(this->prompt_len) : cur_len;
`sequence_group->get_max_new_tokens()` already uses `prompt_len`. I think this should be reverted

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/sequence_group.hpp
> +        return get_context_len() >= get_prompt_len() && get_context_len() > m_max_content_len && m_sampling_params.get_max_new_tokens(get_prompt_len()) > 0;
```suggestion
        return get_context_len() >= get_prompt_len() && get_context_len() > m_max_content_len && get_max_new_tokens() > 0;
```

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/speculative_decoding/continuous_batching_for_speculative_decoding_impl.cpp
> +                     max_new_tokens = request->get_sampling_parameters().get_max_new_tokens(request->get_prompt_len());
```suggestion
                     max_new_tokens = request->get_max_new_tokens();
```

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/speculative_decoding/continuous_batching_for_speculative_decoding_impl.cpp
> +                (request->get_num_processed_tokens() - request->get_prompt_len() + 1) >= sampling_params.get_max_new_tokens(request->get_prompt_len()) - 1) {
```suggestion
                (request->get_num_processed_tokens() - request->get_prompt_len() + 1) >= request->get_max_new_tokens() - 1) {
```

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/speculative_decoding/continuous_batching_for_speculative_decoding_impl.cpp
> +            } else if (sampling_params.get_max_new_tokens(request->get_prompt_len()) == 0) {
```suggestion
            } else if (request->get_max_new_tokens()) == 0) {
```

2025-02-28 09:58 UTC, as-suvorov commented on src/cpp/src/sampler.hpp
> +        size_t prompt_len;
Is this member used?

2025-03-04 08:40 UTC, as-suvorov commented on src/cpp/src/sampler.cpp
> +        group.prompt_len = this->m_sequence_group->get_prompt_len();
Does `Sampler::GroupBeamSearcher::Group` have `prompt_len` member?

2025-03-04 08:46 UTC, as-suvorov approved these changes

2025-03-04 09:01 UTC, ilya-lavrenov commented on src/cpp/src/prompt_lookup/continuous_batching_for_prompt_lookup.cpp
> +                const auto left_generated_len = std::min(request->get_max_new_tokens(), sampling_params.max_length) - generated_len - 1;
I suppose it can be incorrect to take min between `sampling_params.max_length` and `request->get_max_new_tokens()`, because first one assumes prompt 

@iefode should not we use just `request->get_max_new_tokens()` ?

2025-03-04 09:07 UTC, iefode commented on src/cpp/src/prompt_lookup/continuous_batching_for_prompt_lookup.cpp
> +                const auto left_generated_len = std::min(request->get_max_new_tokens(), sampling_params.max_length) - generated_len - 1;
@ilya-lavrenov Correct, thanks!

Looks like we should use:
`const auto left_generated_len = std::min(request->get_max_new_tokens(), sampling_params.max_length - prompt_len) - generated_len - 1;`

2025-03-04 09:08 UTC, iefode commented on src/cpp/src/speculative_decoding/continuous_batching_for_speculative_decoding_impl.cpp
> +                     max_new_tokens = request->get_max_new_tokens();;
```suggestion
                     max_new_tokens = request->get_max_new_tokens();
```

2025-03-04 09:24 UTC, iefode approved these changes

2025-03-04 09:29 UTC, as-suvorov commented on src/cpp/src/prompt_lookup/continuous_batching_for_prompt_lookup.cpp
> +                const auto left_generated_len = std::min(request->get_max_new_tokens(), sampling_params.max_length) - generated_len - 1;
`request`s get_max_new_tokens:
```c++
size_t get_max_new_tokens() const {
    return m_sampling_params.get_max_new_tokens(get_prompt_len());
}
```

`m_sampling_params`s get_max_new_tokens:
```c++
size_t GenerationConfig::get_max_new_tokens(size_t prompt_length) const {
    // max_new_tokens has priority over max_length, only if max_new_tokens was not specified use max_length
    if (max_new_tokens != SIZE_MAX) {
        return max_new_tokens;
    } else {
        return max_length - prompt_length;
    }
}
```

It looks we can use just `request->get_max_new_tokens()`

2025-03-04 10:21 UTC, ilya-lavrenov commented on src/cpp/src/prompt_lookup/continuous_batching_for_prompt_lookup.cpp
> +                const auto left_generated_len = std::min(request->get_max_new_tokens(), sampling_params.max_length) - generated_len - 1;
@michalkulakowski please, take into account details above from Alexander

2025-03-04 11:48 UTC, ilya-lavrenov commented
build_jenkins

2025-03-04 11:48 UTC, ilya-lavrenov approved these changes

2025-03-04 11:56 UTC, ilya-lavrenov commented
Please, fix compilation

2025-03-05 13:54 UTC, ilya-lavrenov commented
build_jenkins

2025-03-05 17:57 UTC, merged