Add code quality checks to GitHub Actions
openvinotoolkit/openvino.genai pull request #1453
Opened 2024-12-30 10:36 UTC by Cyber-Var

Addresses: Good First Issue #663 

Changes made:
- Removed trailing whitespaces where necessary (excluding .md and hidden files). 
- And removed unnecessary non-ASCII symbols (also excluding .md and hidden files).
- Added a new job (**code-quality-checks**) within the GitHub Actions workflow that runs 3 checks automatically (it checks for trailing whitespaces and non-ASCII symbols in files and filenames excluding those ones where it's expected.

2024-12-30 14:42 UTC, ilya-lavrenov commented on .github/workflows/causal_lm_cpp.yml
> +        run: ! git grep -n '[^ -~±�]' -- $(git ls-files | grep -vE '^\.' | grep -vE '\.md$' | grep -vE '^(tests/python_tests|tools/who_what_benchmark/(tests|whowhatbench))' | grep -v 'tools/llm_bench
is it possible to use some existing tools instead of manual commands?

2025-01-01 07:02 UTC, Cyber-Var commented on .github/workflows/causal_lm_cpp.yml
> +        run: ! git grep -n '[^ -~±�]' -- $(git ls-files | grep -vE '^\.' | grep -vE '\.md$' | grep -vE '^(tests/python_tests|tools/who_what_benchmark/(tests|whowhatbench))' | grep -v 'tools/llm_bench
I will look for some

2025-01-02 16:21 UTC, Cyber-Var commented on .github/workflows/causal_lm_cpp.yml
> +        run: ! git grep -n '[^ -~±�]' -- $(git ls-files | grep -vE '^\.' | grep -vE '\.md$' | grep -vE '^(tests/python_tests|tools/who_what_benchmark/(tests|whowhatbench))' | grep -v 'tools/llm_bench
@ilya-lavrenov , I've updated the pull request. 

The causal_lm_cpp.yml workflow now uses .pre-commit-config.yaml for running pre-commit hooks instead of manual commands. They:
• Remove trailing whitespaces
• Ensure files end with a newline

Additionally, I've added new pre-commit hooks to:
• Validate JSON files for syntax correctness
• Detect merge conflict markers

For non-ASCII character checks, I've introduced custom scripts located in the pre_commit_scripts folder, as I couldn't find suitable existing tools. These scripts are integrated and managed through the same .pre-commit-config.yaml.

Please review the changes and let me know if further adjustments are needed.

2025-01-06 08:47 UTC, Wovchena reviewed
I'm OK with `pre-commit` usage

2025-01-06 08:47 UTC, Wovchena commented on .pre-commit-config.yaml
> +        exclude: '(\.md$|^\.|/\.+)'
Why are .md and hidden files excluded instead of being fixed? Same for trailing-whitespace

2025-01-06 08:47 UTC, Wovchena commented on .pre-commit-config.yaml
> +        exclude: '(\.md$|^\.|/\.+)'
Can you explain the last alternative of the regexp?
`\.md$` is anything ending with .md
`^\.` is anything starting with .
But what is `/\.+` for?

2025-01-06 10:38 UTC, Cyber-Var commented on .pre-commit-config.yaml
> +        exclude: '(\.md$|^\.|/\.+)'
@Wovchena , I excluded .md files from fixing trailing whitespaces, cause in Markdown two spaces at the end of a line create a line break, and removing them would result in formatting issues. However, I just changed the code not to exclude them from the end-of-file-fixer. 
As for hidden files, most of them are related to git configurations. When I tested without excluding them, I wasn't able to commit anything afterwards, cause it broke something in the git process. However, now I changed the code to only exclude hidden files related to git. 
If you think all hidden files and .md files should still be included in all checks, I'm open to making that change. Please let me know.

2025-01-06 10:43 UTC, Cyber-Var commented on .pre-commit-config.yaml
> +        exclude: '(\.md$|^\.|/\.+)'
@Wovchena , I wanted the regexp to match any hidden file or folder at any level. However, /\./+ seems to be an error I made. Thank you for catching that!
Nevertheless, I modified the regexp to only exclude hidden files related to git, so should be without errors now.

2025-01-06 10:50 UTC, Wovchena approved these changes
Thank you! Let's wait for @ilya-lavrenov's review. You'll also need to resolve the conflicts.

2025-01-06 10:56 UTC, Cyber-Var commented
@Wovchena, thank you for the approval! I'll address the conflicts.

2025-01-08 14:53 UTC, Cyber-Var commented on src/python/openvino_genai/py_openvino_genai.pyi
@Wovchena, I regenerated `py_openvino_genai.pyi` as requested. Please review the changes.

2025-01-09 05:38 UTC, ilya-lavrenov requested changes

2025-01-09 05:38 UTC, ilya-lavrenov commented on thirdparty/openvino_tokenizers
could you please revert submodule update?

2025-01-09 05:38 UTC, ilya-lavrenov commented on src/python/openvino_genai/py_openvino_genai.pyi
> +    def add(self, arg0: Adapter, arg1: float) -> AdapterConfig:
looks like is generated with old GenAI

2025-01-09 05:38 UTC, ilya-lavrenov commented on CMakeLists.txt
> +        VERSION 2024.5.0.0
please, revert

2025-01-09 08:26 UTC, Cyber-Var commented
@ilya-lavrenov , I noticed that my local changes were causing many issues. So, instead of reverting the specific changes as you requested, I completely removed all my previous changes. 
After resetting everything, I re-added my code from scratch to ensure it aligns with the latest version of the repo. 
Please review the updated changes.

2025-01-28 09:49 UTC, Cyber-Var commented
@ilya-lavrenov , I've reset everything again and I re-added my code from scratch to ensure it aligns with the latest version of the repo.
Please review the updated changes.

2025-01-31 11:00 UTC, Wovchena commented
https://github.com/openvinotoolkit/openvino.genai/pull/1453#discussion_r1904157511 still needs a fix

2025-03-03 08:50 UTC, closed without merging