Red pjama 3b instruct
openvinotoolkit/openvino.genai pull request #352
Opened 2024-04-09 18:16 UTC by akiseakusa

This should close https://github.com/openvinotoolkit/openvino.genai/issues/276 , I have updated the model list , and added tests taking reference from issue description at https://github.com/openvinotoolkit/openvino.genai/issues/259 , @p-wysocki @ilya-lavrenov @pavel-esir in the readme I have added Red pjama 3b separately along with that huggingface comparison has also added. please let me know if anything else can be done.

2024-04-09 18:48 UTC, ilya-lavrenov commented
Please, resolve merge conflicts.

2024-04-15 09:15 UTC, ilya-lavrenov commented
Please, resolve merge conflicts

2024-04-28 17:41 UTC, akiseakusa commented
@ilya-lavrenov Sorry for the delay,I have resolved the conflict. please check.

2024-04-29 10:15 UTC, Wovchena requested changes

2024-04-29 10:15 UTC, Wovchena commented on .github/workflows/causal_lm_cpp.yml
> +    runs-on: ubuntu-20.04-16-cores
```suggestion
    runs-on: ubuntu-20.04
```
Can you try the smaller runner?

2024-04-29 10:15 UTC, Wovchena commented on .github/workflows/causal_lm_cpp.yml
> +          timeout 50s ./build/beam_search_causal_lm .RedPajama-INCITE-Instruct-3B-v1/pytorch/dldt/FP16/ 69 > ./pred.txt
```suggestion
          timeout 50s ./build/beam_search_causal_lm ./RedPajama-INCITE-Instruct-3B-v1/pytorch/dldt/FP16/ 69 > ./pred.txt
```

2024-04-29 10:15 UTC, Wovchena commented on .github/workflows/causal_lm_cpp.yml
> +  cpp-beam_search_causal_lm-Mistral-7B:
I believe it won't ever pass, please remove it. https://github.com/openvinotoolkit/openvino.genai/pull/371

2024-04-29 10:15 UTC, Wovchena commented on .github/workflows/causal_lm_cpp.yml
> -  cpp-greedy_causal_lm-redpajama-3b-chat:
Why do you remove it? Can you merge it with your test implementation

2024-04-29 10:15 UTC, Wovchena commented on text_generation/causal_lm/cpp/README.md
> -11. [redpajama-3b-chat](https://huggingface.co/ikala/redpajama-3b-chat)
Why do you remove [redpajama-3b-chat](https://huggingface.co/ikala/redpajama-3b-chat)?

2024-05-03 16:09 UTC, andrei-kochin commented
@akiseakusa could you please apply the comments?

2024-06-14 16:47 UTC, closed without merging