Move from image_generation python conversion scripts to optimum-cli (LCM Dreamshaper v7 model)
openvinotoolkit/openvino.genai pull request #380
Opened 2024-04-23 17:08 UTC by yatarkan

CVS-132863

2024-04-24 14:42 UTC, Wovchena requested changes

2024-04-24 14:42 UTC, Wovchena commented on image_generation/lcm_dreamshaper_v7/cpp/README.md
>  ```shell
```suggestion
```shell
conda upgrade -c conda-forge --all
```

I had the compilation error without it when installing tokenizers: /home/wov/anaconda3/envs/openvino_lcm_cpp/x86_64-conda-linux-gnu/include/c++/11.2.0/ctime:80:11: error: 'timespec_get' has not been declared in '::'

Can you update stable diffusion the same way?

2024-04-26 14:22 UTC, yatarkan commented on image_generation/lcm_dreamshaper_v7/cpp/README.md
>  ```shell
Added

2024-04-27 06:54 UTC, Wovchena approved these changes

2024-04-27 09:46 UTC, ilya-lavrenov approved these changes

2024-04-27 09:46 UTC, merged

2024-04-27 11:35 UTC, ilya-lavrenov commented
Looks like we need to port these changes to 2024.1 and master