Consume all draft tokens for speculative decoding
openvinotoolkit/openvino.genai pull request #424
Opened 2024-05-08 08:46 UTC by as-suvorov

Ticket: 140110

2024-05-08 09:33 UTC, Wovchena requested changes
I believe your code comments are pretty clear!

2024-05-08 09:33 UTC, Wovchena commented on text_generation/causal_lm/cpp/speculative_decoding_lm.cpp
> +       match the target. In tha caste the are validated in a single inference request to
```suggestion
       match the target. In that case they are validated in a single inference call to
```
"inference request" collides with ov::InferRequest

2024-05-08 11:41 UTC, as-suvorov commented on text_generation/causal_lm/cpp/speculative_decoding_lm.cpp
> +       match the target. In tha caste the are validated in a single inference request to
applied

2024-05-08 11:42 UTC, as-suvorov commented on text_generation/causal_lm/cpp/speculative_decoding_lm.cpp
> +       the main model (which is bigger, more accurate but slower) instead of running K
moved to main_model assignment

2024-05-08 11:42 UTC, as-suvorov commented on text_generation/causal_lm/cpp/speculative_decoding_lm.cpp
> +
applied

2024-05-08 11:42 UTC, as-suvorov commented on text_generation/causal_lm/cpp/speculative_decoding_lm.cpp
> +            // if out_of_kv_cache_token present - prepend it to out_token in order to collect kv cache for it
applied

2024-05-08 11:44 UTC, Wovchena approved these changes

2024-05-09 06:16 UTC, pavel-esir approved these changes

2024-05-09 07:39 UTC, merged