Control KV-cache size for StaticLLMPipeline
openvinotoolkit/openvino.genai pull request #795
Opened 2024-08-26 09:04 UTC by TolyaTalamanov

2024-08-26 10:54 UTC, dmatveev approved these changes
LGTM

2024-08-26 13:21 UTC, Wovchena requested changes
You are very verbose in PR description and completely ignore the actual docstrings and readmes which are the actual stuff that is read. Please, update them.

2024-08-26 15:38 UTC, TolyaTalamanov commented
> You are very verbose in PR description and completely ignore the actual docstrings and readmes which are the actual stuff that is read. Please, update them.

I don't think we have any readme as part of this repo. I believe we may have one but will it block the PR to get into release for now?

For now our main doc is located there: https://docs.openvino.ai/nightly/learn-openvino/llm_inference_guide/genai-guide-npu.html

2024-08-27 08:48 UTC, Wovchena approved these changes

2024-08-27 11:49 UTC, merged