Fixed regression in multinomial.
openvinotoolkit/openvino.genai pull request #889
Opened 2024-09-23 07:42 UTC by popovaan

Fixed regression after https://github.com/openvinotoolkit/openvino.genai/pull/886.

2024-09-23 14:58 UTC, mzegla approved these changes

2024-09-24 08:16 UTC, dtrawins requested changes
it works in greedy search but there are incorrect generations in multinomial algorithm

2024-09-24 13:28 UTC, dtrawins approved these changes

2024-09-25 09:01 UTC, iefode approved these changes
LGTM

2024-09-25 10:29 UTC, merged