✨ Run pre-commit checks and fix issues in GenAI code style #663
openvinotoolkit/openvino.genai pull request #905
Opened 2024-09-27 13:35 UTC by LitZeus

### 🛠️ Implemented basic pre-commit checks to improve code quality across the project

🔍 **Added checks for:**
   - flake8 for linting
   - isort for import organization
   - mypy for type checking

🔧 Fixed detected code style issues and excluded expected failures (e.g., non-ASCII symbols in README.md) to maintain testing integrity.

🔗 This resolves issue #663 by establishing a consistent coding style and enhancing maintainability.

2024-09-30 07:29 UTC, Wovchena requested changes

2024-09-30 07:29 UTC, Wovchena commented on .github/workflows/causal_lm_cpp.yml
> +
It seems you've included all `.md`. Can it be `(exclude)**/*.md`?

2024-09-30 07:29 UTC, Wovchena commented on thirdparty/openvino_tokenizers
We need the submoudle

2024-09-30 07:29 UTC, Wovchena commented on tests/python_tests/test_chat_generate_api.py
> +>>>>>>> Stashed changes
That's why you shouldn't have extended the task with other code style checks. It becomes hard to manage.

Resolve the conflict.

2024-09-30 07:29 UTC, Wovchena commented on .github/workflows/causal_lm_cpp.yml
> +        run: black --check .
Please, align the code style requirements with the main repo https://github.com/openvinotoolkit/openvino if you are going to keep this.

2024-11-06 07:00 UTC, mlukasze commented
hey @LitZeus  will you have a time to solve issues with the PR?

2024-11-06 07:00 UTC, closed without merging