Update README.md
openvinotoolkit/openvino.genai pull request #978
Opened 2024-10-15 17:55 UTC by raymondlo84

Quick patch to the chatbot_readme README and reference to the blog.

2024-10-15 18:32 UTC, ilya-lavrenov commented on samples/python/chat_sample/README.md
> +device = 'GPU'  # GPU can be used as well
```suggestion
device = 'CPU'  # GPU can be used as well
```

2024-10-18 08:20 UTC, ilya-lavrenov approved these changes

2024-10-18 09:34 UTC, Wovchena requested changes

2024-10-18 09:34 UTC, Wovchena commented on samples/python/chat_sample/README.md
> +pipe = openvino_genai.LLMPipeline(args.model_dir, device)
If you believe that should be shown in readme, you must do that for every sample.

2024-10-18 09:34 UTC, Wovchena commented on samples/python/chat_sample/README.md
Update C++ version the same way

2024-12-23 12:43 UTC, closed without merging