[JUST FOR REVIEW] Input embedder
openvinotoolkit/openvino.genai pull request #985
Opened 2024-10-16 11:56 UTC by ilya-lavrenov

Based on https://github.com/openvinotoolkit/openvino.genai/pull/981

2024-10-17 10:58 UTC, Wovchena requested changes
Accuracy test diverged

2024-10-17 10:58 UTC, Wovchena commented on src/cpp/src/visual_language/input_embedder.cpp
> +    ov::Tensor concatenate_mid_dim(const ov::Tensor& first, const ov::Tensor& second) {
It seems it's no longer used.

2024-10-17 10:58 UTC, Wovchena commented on src/cpp/src/visual_language/pipeline.cpp
> +        OPENVINO_ASSERT(!m_is_chat_conversation, "Chat template cannot be changed once start_chat() is called. Please, finish current chat via finish_chat()");
That's no what docstrings state :)
```
    /// applies chat_template to input prompts. Calling start_chat()
    /// again or finish_chat() drops the memorized history.
```
Update it please.

2024-10-17 12:43 UTC, ilya-lavrenov commented on src/cpp/src/visual_language/input_embedder.cpp
> +    ov::Tensor concatenate_mid_dim(const ov::Tensor& first, const ov::Tensor& second) {
dropped

2024-10-18 08:07 UTC, Wovchena approved these changes

2024-10-18 09:13 UTC, merged